#ifndef DIRECTION
#define DIRECTION

enum DIR {NODIR, TOP, BOTTOM, LEFT, RIGHT};
enum PNT {NOPNT,
		  TOPLEFT, TOPMID, TOPRIGHT,
		  MIDLEFT, CENTER, MIDRIGHT,
		  BOTLEFT, BOTMID, BOTRIGHT};


#endif